services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '2821:2821'
    depends_on:
      - rabbitmq
  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: npm run start:dev product
    env_file:
      - ./apps/product/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/product/.env
    depends_on:
      - mysqldb
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
  mysqldb:
    image: mysql:8.0.1
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=microservices
    volumes:
      - mysqldata:/var/lib/mysql
  phpadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysqldb
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      - mysqldb
volumes:
  mongodata:
    driver: local
  mysqldata:
